version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, do not build your docs in additional formats
formats: []

# Set the OS
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt
